### ISSUE TITLE
Set _NET_WM_WINDOW_TYPE before mapping the window

### ISSUE THREAD

**Issue by Airblader** [Blezzing/blezz#2]
From the [spec](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472629520):

> This SHOULD be set by the Client before mapping to a list of atoms indicating the functional type of the window.

Note that the »SHOULD« refers to setting the property at all; if set, it MUST happen before mapping the window.

**Comment by Blezzing** [comment]
This has now been resolved. Thank you.
