### ISSUE TITLE
Set WM_CLASS

### ISSUE THREAD

**Issue by Airblader** [Blezzing/blezz#3]
Setting `WM_CLASS` (before mapping the window) to a meaningful value allows users to target the window for things like window manager configurations and compositor configurations.

**Comment by Blezzing** [comment]
I made the following call before mapping to the window. 

```xcb_change_property(connection, XCB_PROP_MODE_REPLACE, window, XCB_ATOM_WM_CLASS, XCB_ATOM_STRING, 8, 12, "blezz\0Blezz\0");```

That should do the trick, and inspecting with xprop shows the atoms, so i'll close this. If this is wrong feel free to reopen.

**Comment by Airblader** [comment]
Looks good, although I'd get rid of the magic constant 12 by using `strlen("blezz\0Blezz\0")` instead for clarity (the compiler will inline this on compile-time anyway).

Just two more things in case you didn't know:
* I cannot reopen an issue you closed. :-)
* If you add something like "fixes #3" to the commit message, Github automatically closes the issue when the commit is pushed and will also link the commit in the issue. That way when at some point in the future you look at an issue you can easily find the commit that closed the issue (same thing with pull requests).

**Comment by Blezzing** [comment]
Thanks, i do need some tutoring at times ;) First time i'm using Github on a project where not all contributors are collaborators. Have fixed the magic constant now :)
