### ISSUE TITLE
Don't rely on window configuration to be approved

### ISSUE THREAD

**Issue by Airblader** [Blezzing/blezz#5]
The code currently seems to assume that configuring the window always works. This violates the specs because the window manager may choose to reject or modify this request. Blezz should only change its internal size if the server told it that the size changed.

**Comment by Airblader** [comment]
Just left a comment, the commit is still incorrect. :-)

**Comment by Blezzing** [comment]
I'll be damned, trying to incorporate that in the event handling :)

**Comment by Blezzing** [comment]
I made use of the event now, will you do me the favor of checking if it is done correctly? Used this for reference: https://tronche.com/gui/x/xlib/events/window-state-change/configure.html

**Comment by Airblader** [comment]
Good ol' tronche. Oh the hours I've spent digging through those pages. :-) I've left a few comments on the commit itself.
