### ISSUE TITLE
Crashes or Fails to respond to user input in i3

### ISSUE THREAD

**Issue by HarryBeadle** [Blezzing/blezz#9]
Running i3 on Elementary OS

Works perfectly when run from the command line but when bound to `$mod+D` in `i3config` blezz starts and then crashes. However, sometimes it will start and display my options but wont respond to keyboard input.

[config.txt](https://github.com/Blezzing/blezz/files/769964/config.txt)
[content.txt](https://github.com/Blezzing/blezz/files/769965/content.txt)

**Comment by Blezzing** [comment]
interesting, can you try and run it as follows "blezz > out.txt" and then post your txt file from when it crashes?

**Comment by Blezzing** [comment]
I believe this is fixed with the current version where i waited longer for trying to grab the keyboard. Similar problems earlier also appeared in mate and xfce, and they have been resolved. I have tried to recreate this behaviour, but i am now unable to do so.
